"""Render the v4 landing page to static HTML for GitHub Pages.

GitHub Pages serves static files, but v4 is a Flask template with url_for()
calls and a schedule read from the database. So this renders the page through
the real app, rewrites asset URLs to relative paths, and copies only the
images the page actually uses.

Why render through the app rather than hand-copying the HTML: the page must
stay identical to what Patrick reviewed locally. Rendering it means the
static build cannot silently drift from the live template.

The existing developer showcase is NOT destroyed. It moves to /system/ and
keeps working, because the README links to the site root and a client-facing
page is a different audience from a technical one.
"""
import io
import os
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))

DOCS = ROOT / "docs"
OUT_IMG = DOCS / "img"

import app as A  # noqa: E402

app = A.app
app.config["TESTING"] = True
app.config["SERVER_NAME"] = None


def render_v4():
    with app.test_client() as c:
        r = c.get("/v4")
        if r.status_code != 200:
            raise SystemExit(f"/v4 returned {r.status_code}")
        return r.get_data(as_text=True)


html = render_v4()
print(f"rendered /v4  ({len(html) // 1024} KB)")

# ---- collect the assets the page actually references ---------------------
refs = sorted(set(re.findall(r'/static/([A-Za-z0-9_\-./]+)', html)))
print(f"assets referenced: {len(refs)}")

OUT_IMG.mkdir(parents=True, exist_ok=True)
copied = 0
for rel in refs:
    src = ROOT / "static" / rel
    if not src.is_file():
        print(f"  !! missing {rel}")
        continue
    dst = OUT_IMG / pathlib.Path(rel).name
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    copied += 1
print(f"copied {copied} assets -> docs/img/")

# ---- rewrite URLs for a static host --------------------------------------
# /static/img/x.webp -> img/x.webp   (flattened, matching the copy above)
html = re.sub(r'/static/(?:[A-Za-z0-9_\-./]*/)?([A-Za-z0-9_\-.]+\.(?:webp|png|jpg|jpeg|svg|ico|css|js))',
              r'img/\1', html)

# The members login is a Flask route that does not exist on a static host.
# Point it at the repository instead of leaving a link that 404s in front of
# a client.
REPO = "https://github.com/Epatrick7th/infanta-arena-app"
html = html.replace('href="/login"', f'href="{REPO}" target="_blank" rel="noopener"')

# On the published site the "Members area" footer link would 404 for the same
# reason, and the technical write-up now lives at /system/. Point the footer
# at something that exists.
html = html.replace('<a href="img/login">Members area</a>',
                    '<a href="system/">How the system works</a>')
html = html.replace(f'<a href="{REPO}" target="_blank" rel="noopener">Members area</a>',
                    '<a href="system/">How the system works</a>')

# ---- a note the client will not see, but a maintainer will ---------------
html = html.replace(
    "<head>",
    "<head>\n"
    "<!-- Static build of the v4 landing page, generated by\n"
    "     tools/build-pages.py from templates/landing4.html.\n"
    "     Do not edit this file by hand: rerun the tool instead, or the\n"
    "     published page will drift from the one in the app.\n"
    "     The fight schedule is baked in at build time, so rerun after the\n"
    "     listed dates pass. -->", 1)

(DOCS / "index.html").write_text(html, encoding="utf-8")
print(f"wrote docs/index.html  ({len(html) // 1024} KB)")

total = sum(f.stat().st_size for f in DOCS.rglob("*") if f.is_file())
print(f"docs/ total: {total // 1024} KB")

# ---- say plainly what has been frozen into the page ----------------------
# The schedule is read from the database at build time, so the published
# page shows whatever was upcoming when it was built. Silently shipping a
# stale fight schedule would be worse than an ugly page: someone could
# drive out for a fight that is not on.
import re as _re
from datetime import date as _date

days = _re.findall(r'<div class="d mono">(\d+)</div>', html)
mons = _re.findall(r'<div class="m">([A-Za-z]+)</div>', html)
if days:
    first, last = f"{days[0]} {mons[0]}", f"{days[-1]} {mons[-1]}"
    print("\n" + "!" * 68)
    print(f"  The fight schedule is BAKED IN: {first} to {last}.")
    print(f"  Built on {_date.today():%d %b %Y}. Rerun this tool to refresh it,")
    print("  otherwise the published page will advertise dates that have passed.")
    print("!" * 68)
